Add mark as delivered button in chat
GiftForGood/website pull request #379
Opened 2020-10-11 03:31 UTC by jamessspanggg

2020-10-11 12:44 UTC, jamessspanggg commented on src/components/modal/ConfirmDeliveredModal.js
> +    'I have delivered the items to the beneficiary, please confirm and mark the wish as completed!';
Please check if the following deliveredMessage is appropriate

2020-10-26 06:00 UTC, jinyingtan commented on utils/api/chats.js
> +    chatDoc = await this.getChat(id);
Can just return `this.getChat(id)` as most of the api return after `.get()`

2020-10-26 09:27 UTC, jinyingtan approved these changes
LGTM on API changes

2020-12-04 05:43 UTC, kohchihao requested changes
LGTM but need to update the colors to new format and fix certain merge conflict.

2020-12-13 12:22 UTC, kohchihao approved these changes
LGTM 👍

2020-12-16 03:46 UTC, merged